hosts/arael: use testing Linux kernel (6.6-rc5)
Because 6.5 fails to build the NanoPi R6S/R6C DTS files:
```
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:165.1-13 Label or path combphy0_ps not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:169.1-14 Label or path combphy2_psu not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:333.1-11 Label or path pcie2x1l1 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:350.1-11 Label or path pcie2x1l2 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:793.1-8 Label or path u2phy0 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:797.1-12 Label or path u2phy0_otg not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:802.1-8 Label or path u2phy2 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:806.1-13 Label or path u2phy2_host not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:811.1-16 Label or path usb_host0_ehci not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:815.1-16 Label or path usb_host0_ohci not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:819.1-16 Label or path usb_host0_xhci not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:825.1-12 Label or path usbdp_phy0 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:829.1-15 Label or path usbdp_phy0_u3 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6c.dts:17.1-11 Label or path pcie2x1l2 not found
FATAL ERROR: Syntax error parsing input tree
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>