sachiel: stop using latest kernel, breaks ZFS
```
error: Package ‘zfs-kernel-2.1.4-5.18’ in
  /nix/store/apz5b280q5nrjm5lvbmcr3zkw6n59amf-source/pkgs/os-specific/linux/zfs/default.nix:196
  is marked as broken, refusing to evaluate.
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>