hosts/arael: fix broken DTS build for NanoPi R6S
The removed entries are causing a build failure:
```
  DTC     arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6c.dtb
  DTC     arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dtb
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:793.1-8 Label or path u2phy0 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:797.1-12 Label or path u2phy0_otg not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:819.1-16 Label or path usb_host0_xhci not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:825.1-12 Label or path usbdp_phy0 not found
Error: ../arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6s.dts:829.1-15 Label or path usbdp_phy0_u3 not found
FATAL ERROR: Syntax error parsing input tree
make[3]: *** [../scripts/Makefile.lib:419: arch/arm64/boot/dts/rockchip/rk3588s-nanopi-r6c.dtb] Error 1
```
They seem related to USB and something else, but I don't know enough
about DTS file structure to fix this properly.

Signed-off-by: Jakub Sokołowski <jakub@status.im>