builder: set useDefaultShell = true
Otherwise no shell causes:
```
error: serialised integer 7161674624452356180 is too large for type 'j'
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>